const LOGIN_VISIBLE = "LOGIN_VISIBLE";
const LOGIN_INVISIBLE = "LOGIN_INVISIBLE";
const SHOW_ADD_BEER_PAGE = "SHOW_ADD_BEER_PAGE";
const SHOW_BEER_CARD = "SHOW_BEER_CARD";
const CLOSE_BEER_CARD = "CLOSE_BEER_CARD";
const ADD_BEERS = "ADD_BEERS";
const SORT_BEERS = "SORT_BEERS";
const GET_SORT_TYPE = "GET_SORT_TYPE";
const GET_SEARCH_VALUE = "GET_SEARCH_VALUE";
const DISPLAY_SEARCHED = "DISPLAY_SEARCHED";
const ADD_ACCESS = "ADD_ACCESS";
const GET_LOGIN = "GET_LOGIN";
const GET_PASSWORD = "GET_PASSWORD";

export default {
  LOGIN_VISIBLE,
  LOGIN_INVISIBLE,
  ADD_BEERS,
  SORT_BEERS,
  GET_SORT_TYPE,
  GET_SEARCH_VALUE,
  DISPLAY_SEARCHED,
  SHOW_ADD_BEER_PAGE,
  SHOW_BEER_CARD,
  ADD_ACCESS,
  GET_LOGIN,
  GET_PASSWORD,
  CLOSE_BEER_CARD,
};
