const LOGIN_VISIBLE = "LOGIN_VISIBLE";
const LOGIN_INVISIBLE = "LOGIN_INVISIBLE";
const ADD_BEERS = "ADD_BEERS";
const SORT_BEERS = "SORT_BEERS";
const GET_SORT_TYPE = "GET_SORT_TYPE";
const GET_SEARCH_VALUE = "GET_SEARCH_VALUE";
const DISPLAY_SEARCHED = "DISPLAY_SEARCHED";

export default {
  LOGIN_VISIBLE,
  LOGIN_INVISIBLE,
  ADD_BEERS,
  SORT_BEERS,
  GET_SORT_TYPE,
  GET_SEARCH_VALUE,
  DISPLAY_SEARCHED,
};
